pip install altgraph
pip install asgiref
pip install aspose-pdf
pip install asttokens
pip install async-generator
pip install attrs
pip install backcall
pip install beautifulsoup4
pip install cachetools
pip install certifi
pip install cffi
pip install chardet
pip install charset-normalizer
pip install chromedriver-autoinstaller
pip install chromedriver-binary
pip install chromedriver-binary-auto
pip install chromedriver-py
pip install chromedrivermanager
pip install colorama
pip install contourpy
pip install cycler
pip install DateTime
pip install decorator
pip install display
pip install Django
pip install docutils
pip install EasyProcess
pip install edgedriver-autoinstaller
pip install entrypoint2
pip install et-xmlfile
pip install exceptiongroup
pip install executing
pip install fonttools
pip install future
pip install greenlet
pip install h11
pip install idna
pip install image
pip install ipython
pip install jaconv
pip install jedi
pip install keyboard
pip install kiwisolver
pip install lockfile
pip install matplotlib
pip install matplotlib-inline
pip install mouse
pip install MouseInfo
pip install msedge-selenium-tools
pip install mss
pip install notification
pip install Nuitka
pip install numpy
pip install opencv-python
pip install openpyxl
pip install ordered-set
pip install outcome
pip install packaging
pip install pandas
pip install parso
pip install pdfminer3
pip install pdfrw
pip install pefile
pip install pickleshare
pip install pid
pip install Pillow
pip install pip
pip install plyer
pip install prompt-toolkit
pip install psutil
pip install pure-eval
pip install py2exe
pip install PyAutoGUI
pip install pycparser
pip install pycryptodome
pip install PyGetWindow
pip install Pygments
pip install pyinstaller
pip install pyinstaller-hooks-contrib
pip install PyMsgBox
pip install pyocr
pip install pyodbc
pip install pyparsing
pip install pypdf
pip install PyPDF2
pip install pyperclip
pip install pypiwin32
pip install PyRect
pip install pyscreenshot
pip install PyScreeze
pip install pyserial
pip install PySimpleGUI
pip install PySocks
pip install python-daemon
pip install python-dateutil
pip install python-dotenv
pip install pytweening
pip install pytz
pip install pywin32
pip install pywin32-ctypes
pip install reportlab
pip install requests
pip install selenium
pip install service
pip install setproctitle
pip install setuptools
pip install six
pip install sniffio
pip install sortedcontainers
pip install soupsieve
pip install SQLAlchemy
pip install sqlparse
pip install stack-data
pip install tkinterdnd2
pip install tqdm
pip install traitlets
pip install trio
pip install trio-websocket
pip install typing_extensions
pip install tzdata
pip install urllib3
pip install wcwidth
pip install webdriver-manager
pip install wheel
pip install window
pip install wsproto
pip install xlwings
pip install zope.interface
pip install zstandard
