pip install altgraph
pip install async-generator
pip install attrs
pip install beautifulsoup4
pip install cachetools
pip install certifi
pip install cffi
pip install charset-normalizer
pip install chromedriver-autoinstaller
pip install chromedriver-binary
pip install chromedriver-py
pip install colorama
pip install contourpy
pip install cycler
pip install DateTime
pip install et-xmlfile
pip install fonttools
pip install future
pip install greenlet
pip install h11
pip install idna
pip install jaconv
pip install kiwisolver
pip install matplotlib
pip install mouse
pip install MouseInfo
pip install notification
pip install Nuitka
pip install numpy
pip install openpyxl
pip install ordered-set
pip install outcome
pip install packaging
pip install pandas
pip install pefile
pip install Pillow
pip install plyer
pip install py2exe
pip install PyAutoGUI
pip install pycparser
pip install PyGetWindow
pip install pyinstaller
pip install pyinstaller-hooks-contrib
pip install PyMsgBox
pip install pyodbc
pip install pyparsing
pip install PyPDF2
pip install pyperclip
pip install pypiwin32
pip install PyRect
pip install PyScreeze
pip install PySimpleGUI
pip install PySocks
pip install python-dateutil
pip install python-dotenv
pip install pytweening
pip install pytz
pip install pywin32
pip install pywin32-ctypes
pip install requests
pip install selenium
pip install setuptools
pip install six
pip install sniffio
pip install sortedcontainers
pip install soupsieve
pip install SQLAlchemy
pip install tqdm
pip install trio
pip install trio-websocket
pip install typing_extensions
pip install urllib3
pip install webdriver-manager
pip install wsproto
pip install xlwings
pip install zope.interface
pip install zstandard
